version: "3.4"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: marcosg119/timer-and-friends:client-latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
    networks:
      - webappnetwork
    labels:
      kompose.service.type: nodeport
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: marcosg119/timer-and-friends:server-latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
