apiVersion: apps/v1
kind: Deployment
metadata:
  name: timer-and-friends
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timer-and-friends
  template:
    metadata:
      labels:
        app: timer-and-friends
    spec:
      containers:
        - name: client
          image: marcosg119/timer-and-friends:client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: server
          image: marcosg119/timer-and-friends:server
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
#so cool
--- 

apiVersion: v1
kind: Service
metadata:
  name: timer-and-friends
spec:
  type: LoadBalancer
  selector:
    app: timer-and-friends
  ports:
    - name: http-client
      port: 80
      targetPort: 80
      protocol: TCP
    - name: http-server
      port: 9000
      targetPort: 9000
      protocol: TCP
